### ISSUE TITLE
[Wallet Solution] Integrity checks and Wallet Instance authentication

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#40] opened 2023-06-28 16:05 UTC
Maybe we can also add the check on the rooted device? @grausof

_Originally posted by @fmarino-ipzs in https://github.com/italia/eidas-it-wallet-docs/pull/14#discussion_r1244948685_

**Comment by peppelinux** [comment] 2023-06-28 16:06
@fmarino-ipzs 's

I think that the wallet provider is only able to attest the TEE capability. The Wallet Solution must ensure that the private keys are securely stored.

**Comment by balanza** [comment] 2023-06-28 16:10
The point is on the genuineness of the mobile app. The problem is _sociotechnical_ as it involves legal concerns as well as technical constraints and facilities provided by the Device's OS vendors.

We are investigating possible solutions to that, we'll keep you posted.

**Comment by Sh-Amir** [comment] 2023-06-29 07:31
Concerning the genuineness of the mobile app, can't we rely on the App attestations using the Google Integrity API/iOS device check?

**Comment by grausof** [comment] 2023-07-03 07:47
> Concerning the genuineness of the mobile app, can't we rely on the App attestations using the Google Integrity API/iOS device check?

There is an extensive ongoing discussion regarding this matter that requires further attention. Several issues arise, including concerns about privacy, ensuring universal availability of the service to all citizens, as well as the involvement of non-EU services, among others!

**Comment by Sh-Amir** [comment] 2023-07-03 08:04
> > Concerning the genuineness of the mobile app, can't we rely on the App attestations using the Google Integrity API/iOS device check?
> 
> There is an extensive ongoing discussion regarding this matter that requires further attention. Several issues arise, including concerns about privacy, ensuring universal availability of the service to all citizens, as well as the involvement of non-EU services, among others!

I see. Concerning privacy, can you elaborate on it (I am curious to know about it)?  regarding the availability I agree somehow with it, but if we cannot assume the user has a mobile device with a minimum version of Android/iOS that is needed for the use of these services, we may encounter the same problem for the Secure storage of credentials/keys on the mobile devices as well.

**Comment by grausof** [comment] 2023-07-03 08:07
> > > Concerning the genuineness of the mobile app, can't we rely on the App attestations using the Google Integrity API/iOS device check?
> > 
> > 
> > There is an extensive ongoing discussion regarding this matter that requires further attention. Several issues arise, including concerns about privacy, ensuring universal availability of the service to all citizens, as well as the involvement of non-EU services, among others!
> 
> I see. Concerning privacy, can you elaborate on it (I am curious to know about it)? regarding the availability I agree somehow with it, but if we cannot assume the user has a mobile device with a minimum version of Android/iOS that is needed for the use of these services, we may encounter the same problem for the Secure storage of credentials/keys on the mobile devices as well.

It is possible to check the minimum requirements, the problem is to contact non-EU services such as SafetyNet or App Attest Service for apple. The main privacy issue is related to IP addresses

**Comment by grausof** [comment] 2023-08-08 11:16
I add that the _integrity check_ can also be used as an authentication system of the **Wallet Instanc**e towards the **Wallet Provider.** This way, issuing n attestation will only happen if the integrity check is passed (preventing anyone from getting attestation outside the app). cc @peppelinux

**Comment by Sh-Amir** [comment] 2023-08-08 12:11
> I add that the _integrity check_ can also be used as an authentication system of the **Wallet Instanc**e towards the **Wallet Provider.** This way, issuing n attestation will only happen if the integrity check is passed (preventing anyone from getting attestation outside the app). cc @peppelinux

I would like to recommend the consideration of **key attestation** beside the _integrity check_ as it provides useful information regarding the type of secure area that the user's phone support + basic cryptographic properties of the attested key. This information would be useful to be returned in the Wallet instance Attestation as mentioned by @peppelinux [here](https://github.com/italia/eudi-wallet-it-docs/issues/68#issue-1800548444).

**Comment by peppelinux** [comment] 2024-01-18 14:49
see also: https://github.com/italia/eudi-wallet-it-docs/issues/161

**Comment by grausof** [comment] 2024-01-31 16:19
Duplicated of https://github.com/italia/eudi-wallet-it-docs/issues/161 
I'll close the issue and let's move the discussion there

**Closed as completed by grausof** 2024-01-31 16:19 UTC
Labels: wallet-solution
