### ISSUE TITLE
Define the Term Wallet Trust Evidence and WSCA and PoA

### ISSUE THREAD

**Issue by peppelinux** [italia/eidas-it-wallet-docs#230] opened 2024-03-05 08:59 UTC
Don't we still want to introduce the term Wallet Trust Evidence?

_Originally posted by @grausof in https://github.com/italia/eudi-wallet-it-docs/pull/220#discussion_r1512336689_

**Comment by peppelinux** [comment] 2024-05-15 09:37
and WSCA and Proof of Association.

**Comment by grausof** [comment] 2024-10-30 11:29
Duplicate of https://github.com/italia/eudi-wallet-it-docs/issues/396

**Closed as completed by grausof** 2024-10-30 11:29 UTC
Labels: wallet-solution, editorial
